### ISSUE TITLE
Adjust Roles so that only authorized users can edit documentation

### ISSUE THREAD

**Issue by BigActual** [realbigplugins/rbp-documentation-cpt#10]
Default Author & Contributor permissions include access to Documentation. We either require a special type of role that does not have permission to access/edit Documentation or the role's permissions need to be restricted for these two role types to not include Documentation.

**Comment by d4mation** [comment]
I'll get this set, but I also think I should create a special user role for Guest Authors or otherwise prevent actual _Publishing_ by Guest Authors. While the default Author User Role cannot edit content other than their own, they are able to Publish to their heart's content. I'd rather prevent that.

**Comment by d4mation** [comment]
Pushing this change to Live now. Still need to add in the "About the Author" type stuff to the Theme, but that shouldn't take too long.

**Comment by d4mation** [comment]
There is now a "Guest Author" User Role. Please assign that one to him :+1:

It does not have access to Documentation and can only submit Posts for Review (Places them as Pending).

I used the default WordPress implementation for this rather than the custom one we've used for Clients before so it does not send out an email. However, I figure for this use case a Guest Author will tell us when they've given us content to publish.
